# Generated by Django 6.0.5 on 2026-06-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VagaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Vaga')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
        ),
    ]
